# Generated by Django 5.2 on 2025-05-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_blog_blog_image_alter_blog_publis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publis_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
