# Generated by Django 5.2 on 2025-05-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_blog_publis_date_alter_blog_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publis_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
